# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: nuxt-app
---
# ConfigMap for environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: nuxt-config
  namespace: nuxt-app
data:
  API_BASE_URL: "https://api-medi-dev.mypits.org"
  WEB_SOCKET_URL: "wss://api-medi-dev.mypits.org"
  NUXT_HOST: "0.0.0.0"
  NUXT_PORT: "3000"
---
# Service
apiVersion: v1
kind: Service
metadata:
  namespace: nuxt-app
  name: nuxt-app
  labels:
    app: nuxt-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31080
  selector:
    app: nuxt-app
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nuxt-app
  name: nuxt-app-deployment
  labels:
    app: nuxt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxt-app
  template:
    metadata:
      labels:
        app: nuxt-app
    spec:
      containers:
        - name: nuxt-app
          image: abhijithdockerhub/codebuild:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: nuxt-config
                  key: API_BASE_URL
            - name: WEB_SOCKET_URL
              valueFrom:
                configMapKeyRef:
                  name: nuxt-config
                  key: WEB_SOCKET_URL
            - name: NUXT_HOST
              valueFrom:
                configMapKeyRef:
                  name: nuxt-config
                  key: NUXT_HOST
            - name: NUXT_PORT
              valueFrom:
                configMapKeyRef:
                  name: nuxt-config
                  key: NUXT_PORT
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "600m"
