name: UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build -t ui .

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: ui

  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Gitleaks for secrets scanning
        run: gitleaks detect --source . --report-path=gitleaks-results.sarif --report-format=sarif
      - name: Upload Gitleaks SARIF results
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-results-sarif   # <-- VALID artifact name, no dot
          path: gitleaks-results.sarif   # <-- valid file name
