name: UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
     step: build 
      - uses: actions/checkout@v4
      - name: Build the Docker image
      - run: docker build -t ui .
     step: Trivy scan
      - name: Aqua Security Trivy
      - uses: aquasecurity/trivy-action@0.32.0
      - image-ref:  ui 
       
   
      
    
      
    
  
