name: UI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: "fs"
          format: table
          scan-ref: .
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1 
          
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t abhijithdockerhub/ui:latest .

      - name: Push Docker image to Docker Hub
        run: docker push abhijithdockerhub/ui:latest

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: abhijithdockerhub/ui:latest
          args: --skip-version-check # Optional: suppress version check notices

  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks for secrets scanning
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --source . --report-path=gitleaks-results.sarif --report-format=sarif

      - name: Upload Gitleaks SARIF results
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-results-sarif
          path: gitleaks-results.sarif

